### ISSUE TITLE
love this project but how does it work?

### ISSUE THREAD

**Issue by Charlieis1nsan3** [dinguschan-owo/Helios#11]
I am interested in making my own proxy, do you mind telling me how this works?

**Comment by Charlieis1nsan3** [comment]
is it a cors proxy?

**Comment by Charlieis1nsan3** [comment]
yeah it basically just fetches HTML. of the website. and loads it. its simple. I have made plenty.but none of them could actually run stuff like games

**Comment by dinguschan-owo** [comment]
well not really. you make the fetc request with js, then ask a cors proxy to take your request and make ti look human, then fetch the stuff. its a middleman. but whats ur issue rn

**Comment by Charlieis1nsan3** [comment]
oh, no issues but thanks for the explanation. and some websites load the information incorrectly such as kour.io and stuff

**Comment by dinguschan-owo** [comment]
Can you explain the wrong info loading for me? So I can try and fix it lol

**Comment by Charlieis1nsan3** [comment]
it'll load the site but then it'll just basically load forever. and also when you go Fullscreen sometimes it doesn't;t adjust and it stays small.

**Comment by dinguschan-owo** [comment]
huh, ok. what browser are you usign this in, what link, and is it the lastest version of Helios?

**Comment by Charlieis1nsan3** [comment]
I'm using a data url version

**Comment by dinguschan-owo** [comment]
Ok, data:// blob:// and about://blank versions in my experience often have problems running scripts, so that might be the issue. I am actually working on a fix for data urls, which is why I added session IDs but for now please switch to the offline html file or official website, and please let me know if you still have issues

**Comment by Charlieis1nsan3** [comment]
aight
