### ISSUE TITLE
in what way is this unblockable lol.

### ISSUE THREAD

**Issue by builtbypyro** [dinguschan-owo/Helios#12]
just blocking codetabs.com would block literally all instances of this proxy.....

**Comment by dinguschan-owo** [comment]
@builtbypyro you misunderstand what a cors proxy is. A cors proxy disguises the JAVASCRIPT fetch request with a header that makes it look human and legit. Removing th cors proxis from the code wouldn't stop Helios from working, it would just stop you from fetching sites with bot protection and cors requirements.

**Comment by dinguschan-owo** [comment]
Also, I am not affiliated with codetabs. If you look in the code I am also rotating 4 different cors proxies, so that the JavaScript requests don't get flagged for abuse. Helios is unblockablw in the way that no Helios instances can be blocked, because IT is just pure html and cab be hosted anywhere, or just open the file in browser.

**Comment by dinguschan-owo** [comment]
And one more thing, blocking codetabs, or any other cors proxy,  wouldn't change anything. That would make it so YOU can not visit the site, but it does nothing about JavaScript fetch() requests, which are built in in browsers. Please, @builtbypyro, examine the code closely and ensure you understand how it works before submitting an issue.

**Comment by builtbypyro** [comment]
do you understand the essence of a proxy? it is fundamentally impossible to have an unblockable proxy because of the fact that you will need to have a remote server which is able to fetch the content that is not fetchable by the user, because if the user tried to fetch it, it would be blocked. if said remote server is blocked, it is meaningless if 500 different front-ends are created, because they all rely on that remote-server, in this case, 4 of them.

**Comment by builtbypyro** [comment]
blocking codetabs.com, corsproxy.io, and api.allorgins.win, would block every single instance of helios lol. you are literally just replacing a bare server with a cors proxy, and calling it unblockable. In what way is this more secure than TN lol, in both cases, the users network traffic is being sent to a remote server controlled by an external entity. At least in TN's case, they have encrypted transports which allow your network traffic to actually be private

**Comment by dinguschan-owo** [comment]
you know what @builtbypyro? you make some good points. ill add some encryption, and while a network block could block it, none of the instances could be, and Helios rotates proxies to make it harder to trace. agian though, good points and ill reflesh the rotation method and add encryption :)
