### ISSUE TITLE
PROBLEM

### ISSUE THREAD

**Issue by BlacketGodAlt** [dinguschan-owo/Helios#22]
On the w3spaces.com version, I CANNOT load any webpages. Is this issue new?

**Comment by dinguschan-owo** [comment]
Oh dear, thats not supposed to happen. I havent updated the w3 spcaes link in a while though so its a couple versions behind. let me update tthat and let me know if anythign has changed

**Comment by dinguschan-owo** [comment]
@BlacketGodAlt Did this help?
