### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by dlcasto4** [dinguschan-owo/Helios#27]
When I use the Helios browser and visit any website on Microsoft Edge, the CSS code fails to load on the page.

dlcasto4@gmail.com

**Comment by dinguschan-owo** [comment]
Is this a specific site only or everything

**Comment by dlcasto4** [comment]
every website Besides These URLS helios://start, helios://settings, helios://urls

**Comment by dinguschan-owo** [comment]
Which instance are you using, like which link, file, or custom url

**Comment by dlcasto4** [comment]
http://lunaar.work.gd/
https://helios-browser.vercel.app/

**Comment by dinguschan-owo** [comment]
Ok lunaar.work.gd is not an official link, so that might be the issue on that instance bc there have been a couple bug fixes recently, but the vercel is official. are you sure that you have javasrcipt allowed in your settings for edge?

**Comment by dlcasto4** [comment]
Yes i’m sure that I have JavaScript enabled on Microsoft edge
