### ISSUE TITLE
this is something I need to ask u abt . 

### ISSUE THREAD

**Issue by aztro-leakz** [dinguschan-owo/Helios#8]
hey so in that doc of old proxies you have a chat file in there and I was wondering if you could  help me make a chat for bypazzr. yes I know I discontinued it but I still use it in my school and a chat would be nice. thanks

**Comment by dinguschan-owo** [comment]
Yeah, I could probably help u with that, but you'd have to set up a server or websocket

**Comment by aztro-leakz** [comment]
> Yeah, I could probably help u with that, but you'd have to set up a server or websocket

how would one do that

**Comment by aztro-leakz** [comment]
bc I could run smth prolly

**Comment by aztro-leakz** [comment]
also I found a way to just turn securly of lol using rig tools

**Comment by dinguschan-owo** [comment]
> > Yeah, I could probably help u with that, but you'd have to set up a server or websocket
> 
> how would one do that

youcan use node.js or next.js then use npm install in the shell to install websocket.io and go form there
